"""The documents show exactly what the model computes."""

from __future__ import annotations

from pathlib import Path

import pytest

from evrange import Study, report
from evrange.report import BLOCKS, blocks_in, refresh, short_name, signed
from evrange.validation import Comparison

REPOSITORY = Path(__file__).resolve().parent.parent
DOCUMENTS = {
    "README.md": {"summary", "findings", "accuracy", "ranges", "example"},
    "docs/method.md": {"calibration", "epa", "eu", "charging", "sensitivity"},
}
TABLES = ("calibration", "eu", "epa", "charging", "sensitivity", "summary", "accuracy", "ranges")


def test_accuracy_table(study: Study) -> None:
    # Recomputed from scratch from the raw data without this package, the same statistics came
    # out: EPA 1.2511 % mean, 2.0480 % largest; EU 3.1404 % mean, 8.4934 % largest.
    rows = BLOCKS["accuracy"](study).splitlines()[2:]
    assert rows == [
        "| EPA tests the identification did not use | 8 | 1.3 % | 2.0 % | 8 of 8 |",
        "| EU WLTP consumption and range | 8 | 3.1 % | 8.5 % | 6 of 8 |",
        "| All of them | 16 | 2.2 % | 8.5 % | 14 of 16 |",
    ]


def test_accuracy_table_without_further_epa_measurements(
    study: Study, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(report, "epa_comparisons", lambda s: [])
    rows = report.accuracy_table(study).splitlines()[2:]
    assert [r.split(" | ")[0] for r in rows] == ["| EU WLTP consumption and range", "| All of them"]


@pytest.mark.parametrize(("name", "expected"), DOCUMENTS.items())
def test_documents_are_up_to_date(study: Study, name: str, expected: set[str]) -> None:
    text = (REPOSITORY / name).read_text(encoding="utf-8")
    assert set(blocks_in(text)) == expected
    assert refresh(text, study) == text, f"{name} is stale: run python tools/update_docs.py"


def test_table_blocks_render_tables(study: Study) -> None:
    for name in TABLES:
        lines = BLOCKS[name](study).splitlines()
        assert lines[1].startswith("|---"), name
        widths = {line.count("|") for line in lines}
        assert len(widths) == 1, f"{name}: rows with different column counts"


def test_findings_are_computed(study: Study) -> None:
    text = BLOCKS["findings"](study)
    lines = text.splitlines()
    assert all(line.startswith("- ") for line in lines)
    assert "EPA reports of the Volvo EX30 and Polestar 2 contain 8 further measurements" in text
    assert "largest difference between model and measurement is 2.0 %" in text  # README table
    assert "For the Tesla Model 3 RWD and VW ID.4 Pro the model matches" in text
    assert "Volvo EX30: consumption -8.5 %, range +2.0 %" in text
    assert "Polestar 2: consumption +1.9 %, range -6.9 %" in text


def _eu_rows(study: Study, errors: dict[str, float]) -> list[Comparison]:
    rows = []
    for vehicle in study.vehicles:
        e = errors.get(vehicle.id, 0.0)
        rows.append(Comparison(vehicle.id, "EU consumption", "Wh/km", 100 + e, 100.0))
        rows.append(Comparison(vehicle.id, "EU range", "km", 100 - e, 100.0))
    return rows


def test_findings_when_every_car_agrees(study: Study, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(report, "eu_comparisons", lambda s: _eu_rows(s, {}))
    text = report.findings(study)
    assert "Tesla Model 3 RWD, Volvo EX30, Polestar 2 and VW ID.4 Pro the model matches" in text
    assert "other cars" not in text


def test_findings_when_no_car_or_one_car_agrees(
    study: Study, monkeypatch: pytest.MonkeyPatch
) -> None:
    far = {v.id: 5.0 for v in study.vehicles}
    monkeypatch.setattr(report, "eu_comparisons", lambda s: _eu_rows(s, far))
    assert "the model matches the EU" not in report.findings(study)
    one = dict(far, **{"vw-id4-pro": 1.0})
    monkeypatch.setattr(report, "eu_comparisons", lambda s: _eu_rows(s, one))
    assert "For the VW ID.4 Pro the model matches the EU" in report.findings(study)


def test_findings_without_further_epa_measurements(
    study: Study, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(report, "epa_comparisons", lambda s: [])
    first = report.findings(study).splitlines()[0]
    assert first.endswith("contain no further measurements to check it against.")


def test_example_prints_what_the_model_computes(study: Study) -> None:
    text = BLOCKS["example"](study)
    assert text.startswith("```python\n")
    assert text.endswith("\n```")
    wltc = study.on_cycle("tesla-model3-rwd", "wltc")
    shown = f"# {wltc.battery_wh_per_km:.1f} {study.range_km('tesla-model3-rwd', wltc):.0f}"
    assert shown in text
    # The printed code must run and print exactly the commented results. The code is the
    # README example, generated by report.example() from this repository; no input reaches it.
    code = "\n".join(line for line in text.splitlines()[1:-1] if not line.startswith("#"))
    printed: list[str] = []
    exec(code, {"print": lambda *a: printed.append(" ".join(map(str, a)))})  # noqa: S102
    expected = [
        line[2:] for line in text.splitlines() if line.startswith("# ") and "km/h" not in line
    ]
    assert printed == expected


def test_unknown_block_is_refused(study: Study) -> None:
    text = "<!-- generated: nothing -->\n<!-- end generated -->"
    with pytest.raises(KeyError, match="unknown generated block"):
        refresh(text, study)


@pytest.mark.parametrize(
    "text",
    [
        # an end marker is missing: the first block must not swallow the second one
        "<!-- generated: eu -->\ntext\n<!-- generated: epa -->\n<!-- end generated -->",
        "<!-- generated: eu -->\n<!-- end generated -->\n<!-- end generated -->",
        "<!-- generated: eu -->\n",
    ],
)
def test_unbalanced_markers_are_refused(study: Study, text: str) -> None:
    with pytest.raises(ValueError, match="unbalanced"):
        refresh(text, study)
    with pytest.raises(ValueError, match="unbalanced"):
        blocks_in(text)


def test_empty_block_is_filled_and_text_around_it_kept(study: Study) -> None:
    text = "before\n<!-- generated: charging -->\n<!-- end generated -->\nafter\n"
    filled = refresh(text, study)
    assert filled.startswith("before\n<!-- generated: charging -->\n| Car |")
    assert filled.endswith("\n<!-- end generated -->\nafter\n")
    assert refresh(filled, study) == filled


def test_negative_zero_is_printed_as_zero(study: Study) -> None:
    table = BLOCKS["eu"](study)
    assert "-0.0" not in table
    assert "+0.0" not in table


@pytest.mark.parametrize(
    ("value", "digits", "expected"),
    [
        (2.345, 1, "+2.3"),
        (-6.94, 1, "-6.9"),
        (0.04, 1, "0.0"),
        (-0.04, 1, "0.0"),
        (0.004, 2, "0.00"),
        (-0.004, 2, "0.00"),
        (0.006, 2, "+0.01"),
        (-12.0, 0, "-12"),
    ],
)
def test_signed(value: float, digits: int, expected: str) -> None:
    assert signed(value, digits) == expected


def test_short_names() -> None:
    assert short_name("vw-id4-pro") == "VW ID.4 Pro"
    assert short_name("unknown") == "unknown"
